CREATE TABLE `hotel_booking` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `invoice` VARCHAR(100) NOT NULL,
  `member_id` INTEGER NOT NULL,
  `member_phone` VARCHAR(20) NOT NULL,
  `session_id` VARCHAR(150) NOT NULL,
  `group_id` VARCHAR(150) NOT NULL,
  `property_id` VARCHAR(100) NOT NULL,
  `property_name` VARCHAR(255) NOT NULL,
  `city_name` VARCHAR(150) NOT NULL DEFAULT '',
  `room_name` VARCHAR(255) NOT NULL DEFAULT '',
  `check_in` VARCHAR(20) NOT NULL,
  `check_out` VARCHAR(20) NOT NULL,
  `guest_name` VARCHAR(150) NOT NULL,
  `guest_email` VARCHAR(150) NULL,
  `guest_phone` VARCHAR(30) NULL,
  `total_price` INTEGER UNSIGNED NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  `provider_response` JSON NULL,
  `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` TIMESTAMP(0) NULL,

  UNIQUE INDEX `unique_hotel_invoice`(`invoice`),
  INDEX `idx_hotel_booking_member`(`member_id`, `created_at`),
  INDEX `idx_hotel_booking_status`(`status`, `created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
